### PR TITLE
Fix Navbar position and vertically align the hamburger button

### LINKED ISSUE #160: [Enhancement]: Navbar can be fixed on top
Hey I feel that the Navbar could be fixed at the top . It would be very much convenient for the user. I want to work on the feature. Can I start ?

### PR DESCRIPTION
**Pull request by NilanjanPramanik**
## Description
This PR fix the position of the Navbar to top with scrolling and also align the Hamburger button vertically middle.
Fixes #160 
## Changes Made
Screenshot 2023-10-11 225943

### CODE REVIEW

**Review by Anandsg — CHANGES_REQUESTED** [review]
This is only working for main page, see below screenshots
Screenshot 2023-10-12 at 8 10 28 AM
Screenshot 2023-10-12 at 8 10 37 AM
Screenshot 2023-10-12 at 8 10 44 AM

**Comment by NilanjanPramanik** [comment]
hey @Anandsg  i am fixing it

**Comment by Anandsg** [comment]
Sure create a new PR

**Comment by NilanjanPramanik** [comment]
I have created a new PR .... Please review it kindly

**Pull request closed without merging**
