### PR TITLE
Fixed the images not found

### LINKED ISSUE #229: Improve User-Friendly Error Message for Nonexistent Search Results
Problem:
Currently, when a user searches for items that do not exist, we display a generic error message. This error message doesn't provide a positive user experience and can leave users feeling frustrated or lost.

Suggested Improvement:
We should enhance the user experience by providing a more user-friendly error message along with a relevant image. This will help users understand the situation better and guide them towards a solution or alternative action.
Screenshot 2023-10-14 at 10 40 25 PM

### PR DESCRIPTION
**Pull request by TheShiveshNetwork**
## What does this PR do?
This PR fixes the images for not found pages.

## Screenshots
Screenshot 2023-10-14 232527

Fix #229

### CODE REVIEW

**Review by Anandsg — CHANGES_REQUESTED** [review]
Brother we don't need to add image for favourites that is already implemented by other developer please fork latest changes and add only restaturant image for non existing restaturant items hope u got that!! also i see a bug below would it be possible to resolve?
Screenshot 2023-10-15 at 8 44 47 AM

**Comment by TheShiveshNetwork** [comment]
@Anandsg alright, I understand. I'll try to fix the bug too!

**Comment by TheShiveshNetwork** [comment]
@Anandsg, check this out!

**Comment by Anandsg** [comment]
Looks good now

**Pull request merged**
