### PR TITLE
feat: Implemented scroll to top button

### PR DESCRIPTION
**Pull request by shubho0908**
Feature added #38 

Hey @Anandsg 
I have added a scroll to the top button which scrolls the page to the top when clicked on it.

### CODE REVIEW

**Review by Anandsg — CHANGES_REQUESTED** [review]
Could we reduce the size of the scroll-top icon slightly and change its background color to vibrant orange? Our app currently uses a basic color scheme, and while the current design is okay, this change could make it look better. It's up to you whether you'd like to merge this PR as it is or if you'd like to make further adjustments to the icon to improve its appearance

**Comment by shubho0908** [comment]
> Could we reduce the size of the scroll-top icon slightly and change its background color to vibrant orange? Our app currently uses a basic color scheme, and while the current design is okay, this change could make it look better. It's up to you whether you'd like to merge this PR as it is or if you'd like to make further adjustments to the icon to improve its appearance

Please check, if it is good now.

**Review by Anandsg — COMMENTED** [review]
@shubho0908 Can you resolve the conflict

**Comment by shubho0908** [comment]
> @shubho0908 Can you resolve the conflict

@Anandsg Done 👍

**Pull request merged**
