### PR TITLE
ADDED SCROLL TO TOP PERCENTAGE ANIMATION

### PR DESCRIPTION
**Pull request by prakhar1535**
https://github.com/Anandsg/Hungry-hero/assets/113304996/d9c60f86-5b6e-45d7-b948-f77231c2dddc

### CODE REVIEW

**Comment by Anandsg** [comment]
please can you use the same icon with same size you make scroll to top icon little big and that ultimately looking ugly

**Comment by prakhar1535** [comment]
the size is same as before when we scroll to top and its not changing, does the animation looks ugly ?

**Comment by Anandsg** [comment]
No not that much but i see this animation size got liitle bigger you can check main site and use the same size

**Comment by prakhar1535** [comment]
May be it is looking in video but I haven’t added any size factor to change when clicked.

**Comment by prakhar1535** [comment]
> No not that much but i see this animation size got liitle bigger you can check main site and use the same size

- i will make the button little smaller then

**Comment by prakhar1535** [comment]
Screenshot 2023-10-09 170848
i have decreased the size of button

**Comment by Anandsg** [comment]
can u create a new PR i dont see your changes in preview link also please resolve conflict

**Comment by prakhar1535** [comment]
i have added a new pr kindly preview

**Comment by Anandsg** [comment]
i dont see ur new PR can u check again

**Pull request closed without merging**
