### PR TITLE
feat(filter-rating-dropdown): filter by rating

### PR DESCRIPTION
**Pull request by Brij247**
**Acceptance Criteria:**
- Users can easily filter restaurant cards by clicking the Rating button itself.
- Users should be able to filter by different rating ranges, such as 3+ or 2+ ratings, and can see corresponding restaurant cards.
- Reset option is also available to reset the filtered restaurant cards.

### CODE REVIEW

**Review by Anandsg — CHANGES_REQUESTED** [review]
"The changes look good; I have a few suggestions to consider:

- Firstly, there seems to be a delay in rendering when a user clicks on 2+ or 3+ ratings. It takes a few seconds to load the cards, which can lead to a suboptimal user experience. I recommend testing it yourself to see the impact.
- Secondly, there's an issue where the favorite error message appears when filtered ratings are not found (for example, when filtering 2+ rating items). This message might not be necessary in such cases.
- Please consider adding some CSS styling to improve the appearance of the dropdowns; they don't quite match the app's design.
- It would be a good idea to make your filtered buttons cursor pointers for better user interaction.
- I've noticed that the buttons look quite large. If you're having trouble creating a dropdown, you could explore using a popup to present these filter options more elegantly.
- When a user attempts to filter ratings that don't exist, consider displaying a more appropriate message instead of rendering the favourite feature function.
- When user selects an rating option it is not automatically filtering the items, again user needs to click on the button he has selected, this needs to be fixed please!!

I'll go ahead and close this PR; please create a new one. Thanks!"

**Comment by Anandsg** [comment]
@Brij247 also would it be possible to create a new component for your changes?

**Comment by Brij247** [comment]
@Anandsg Great suggestions. Will work on it.

**Comment by Anandsg** [comment]
As already discussed closing this PR please open fresh PR

**Pull request closed without merging**
