### PR TITLE
Solved Accordion Not Collapsing When Hide Button Clicked

### PR DESCRIPTION
**Pull request by ronisarkarexe**
Issue:
closes: https://github.com/Anandsg/Hungry-hero/issues/9

This PR does:

When the "Hide" button is clicked, the content hide
When the "Show" button is clicked, the content show
Screenshot:

By default looks like
imgdefault

when click show button, content show
img1

when click hide button, content hide
img2

### CODE REVIEW

**Comment by Anandsg** [comment]
@ronisarkarexe The collapse feature is working well, but it has trouble when we try to view only one questionnaire at a time.. If you see the last deployment, you'll notice that we should only open one questionnaire at a time. Can you please check and make sure it doesn't affect other functions?

**Comment by ronisarkarexe** [comment]
> @ronisarkarexe The collapse feature is working well, but it has trouble when we try to view only one questionnaire at a time.. If you see the last deployment, you'll notice that we should only open one questionnaire at a time. Can you please check and make sure it doesn't affect other functions?

I verified that by default only one questionnaire is displayed. When attempting to open another questionnaire, the previous one is automatically hidden, and the current questionnaire is the only one in focus. when current questionnaire open hide is not working well.

So, how I solved it?
1. at a time we can show and hide questionnaire.

i reviewed this method it works well. 


Note: are you looking for at a time only one questionnaire and hide button also work? mean when the Hide button is clicked content should hide??

Or can you please check my changes once? thank you

**Comment by Anandsg** [comment]
@ronisarkarexe agree that the hide feature works well, great work there! it's crucial that our main focus remains on point. We should ensure that only one questionnaire opens at a time and that it hides as expected when we need it to.

Let's dive back into the code and fine-tune this one-questionnaire-at-a-time functionality.

you can check below link for the exact functionality. if you need any assistance please circle back
https://www.swiggy.com/support

**Comment by ronisarkarexe** [comment]
> @ronisarkarexe agree that the hide feature works well, great work there! it's crucial that our main focus remains on point. We should ensure that only one questionnaire opens at a time and that it hides as expected when we need it to.
> 
> Let's dive back into the code and fine-tune this one-questionnaire-at-a-time functionality.
> 
> you can check below link for the exact functionality. if you need any assistance please circle back https://www.swiggy.com/support

please check it now.

**Comment by Anandsg** [comment]
> https://app.netlify.com/sites/hungry-hero-ag/deploys/651998cda37c590008c57d54



> > @ronisarkarexe agree that the hide feature works well, great work there! it's crucial that our main focus remains on point. We should ensure that only one questionnaire opens at a time and that it hides as expected when we need it to.
> > Let's dive back into the code and fine-tune this one-questionnaire-at-a-time functionality.
> > you can check below link for the exact functionality. if you need any assistance please circle back https://www.swiggy.com/support
> 
> please check it now.

Perfect this looks good, you were able to make it simple.

**Pull request merged**
