### PR TITLE
 Feature: Navbar fixed for mobile screen

### LINKED ISSUE #197: [Feature] : Enhance the style of nav links for mobile screen
The nav buttons for the mobile screen can have a better styling. I want to work on this feature

### PR DESCRIPTION
**Pull request by NilanjanPramanik**
This PR optimized the navbar for the mobile screen. 
Fixes #197

### CODE REVIEW

**Comment by NilanjanPramanik** [comment]
Hey @Anandsg anything can be improve in my PR please let me know ..... I will change it accordingly

**Comment by Anandsg** [comment]
Brother sorry to bother you, did we made nav bar font bold in big screen ? this is not needed keep it as  before in big screen no need to change anything, your work is to just make responsiveness for small devices 

Screenshot 2023-10-14 at 8 17 56 AM

**Comment by NilanjanPramanik** [comment]
@Anandsg  Surely...

**Comment by NilanjanPramanik** [comment]
Hey @Anandsg  I have sync the code just 20 minutes ago and I have update the code in PR. 
I have removed the hamburger icon and delete the code for mobile screen that is written separately.
## Conflict file
Screenshot 2023-10-14 094709
## My code
Screenshot 2023-10-14 094727

**Pull request closed without merging**
