### PR TITLE
[feat]: Consequent focus functionality - Contact Component

### LINKED ISSUE #221: [feat]: Sequential focus functionality for contact component
@Anandsg 

I have worked on improving the user experience in the contact component.

For this PR, Our contact component sets the focus for next,next input on pressing the enter key.

Please refer this video [Contact Component Sequential Focus](https://drive.google.com/file/d/1Zih0yVcCh6JhX3y7F7lPc5gY4iUz3jov/view?usp=sharing)

(In the video i will press enter as soon as i finished entering the inputs)

Can you assign this to me ? 

Will create a PR now, as it is mergeable.

### PR DESCRIPTION
**Pull request by Prakash-Ravichandran**
@Anandsg 

Creating a PR for contact component for sequential focus functionality.

closes #221 

Kindly review & approve my PR.

### CODE REVIEW

**Review by Anandsg — CHANGES_REQUESTED** [review]
Okay this make sense, but when a user inputs integer as their name or an invalid email and presses 'Enter' again, the cursor jumps to the next input. This might not provide the best user experience. Ideally, when a user inputs a valid name or email then only it should move to the next input.

**Comment by Prakash-Ravichandran** [comment]
I am working on the issue.

**Comment by TheShiveshNetwork** [comment]
@Prakash-Ravichandran instead of directly writing `input` tags, wrap them inside a `form` and give a submit button. That might fix the issue, I guess!

**Comment by Prakash-Ravichandran** [comment]
Let me try

**Comment by Prakash-Ravichandran** [comment]
@Anandsg 

I have made the changes which you have requested:

Refer the video - [changes made for PR video](https://drive.google.com/file/d/1msW1QRYYPmqVX7SxJtp5fWnAlWlg7hKX/view?usp=drive_link)

Kindly review & accept my PR

**Comment by Anandsg** [comment]
Works fine now, can we please remove consoles and resolve attached error 
Screenshot 2023-10-15 at 5 11 35 PM

**Comment by Prakash-Ravichandran** [comment]
@Anandsg 

Removed consoles, Fixed the reference error.

**Pull request merged**
