### PR TITLE
#36 [feature request]  : Improve Responsiveness of Restaurant Cards and Search Box, and Buttons

### PR DESCRIPTION
**Pull request by mhamzanadeem**
**Header**
I have added feature of responsiveness in search , button and restaraunt cards 
**body**
I am particapting in hacktoberfest 2023 . 
I have try my best to add this feature .
If some feature is not implement correctly , i will review my contribution again

### CODE REVIEW

**Review by Anandsg — CHANGES_REQUESTED** [review]
While the responsiveness improvements for restaurant cards are on point, I'd recommend reverting the search box, rating, and favorites to their original positions; they don't seem to align practically. Additionally, let's bring back the original font size for ratings in restaurant cards. **The only change I'd like to keep is the responsiveness for restaurant cards**, i have marked as well that you need to revert from current changes

Screenshot 2023-10-05 at 11 11 07 PM

**Comment by mhamzanadeem** [comment]
I have done changes as you have mentioned 
1. revert the position of search button (only in larger screen) .
2. revert the size of rating in restaraunt cards

**Review by Anandsg — CHANGES_REQUESTED** [review]
Brother i have suggested to revert all the changes including search box, ratings and favourites since these are looking quite bad with UX practicaly, please make PR only with responsiveness changes of small devices hope u got it.

Bring them back like below 
Screenshot 2023-10-05 at 11 33 55 PM

**Comment by mhamzanadeem** [comment]
@Anandsg  sir i have reverted search button and search box as you have mentioned according to your given picture

**Review by Anandsg — APPROVED** [review]
Res cards looks good in small devices

**Pull request merged**
