### PR TITLE
Added Dark Mode and Fixes Buttons BG #107

### PR DESCRIPTION
**Pull request by Rahul-Roy-Hub**
[Feature request] : Implement Dark Mode #107
HungryHero

### CODE REVIEW

**Review by Anandsg — CHANGES_REQUESTED** [review]
This looks good, Is there any way we can add the logo without white bg to match the header? It's not vibing well right now. Also, what's the deal with the menu page? I don't see a dark mode option there. Check out the logo I attached without the background

https://www.creativefabrica.com/wp-content/uploads/2018/10/Fast-Delivery-food-logo-by-DEEMKA-STUDIO-580x406.jpg

**Comment by Rahul-Roy-Hub** [comment]
@Anandsg Ok now I will get the Logo JPG file without background it will change soon and also work on menu thing.

**Comment by Rahul-Roy-Hub** [comment]
@Anandsg Done with Logo and Menu Page and some buttons background also fixed.

**Comment by Anandsg** [comment]
looks good can you resolve the conflict

**Comment by Rahul-Roy-Hub** [comment]
Hey now see my main branch is all good.

**Pull request merged**
