### PR TITLE
[Feature] : Enhance the user experience when page not found

### LINKED ISSUE #65: Enhance user experience for Non-Existent restaurant rearches
Currently, when a user searches for a restaurant that doesn't exist in our application, they are presented with a plain message stating, "The restaurant you're searching for doesn't exist," along with a button to navigate back to the home page. This minimalistic approach, while functional, may not provide the best user experience.

**Proposed Enhancement:**
We should improve the user experience by introducing some form of visual feedback to make the experience more engaging and informative.

**Error Icon/Graphic: I** instead of a plain text message, we could display an error icon or graphic (e.g., a sad face or a restaurant with a "not found" sign) to convey the message more visually.

Screenshot 2023-10-05 at 10 16 41 AM

### PR DESCRIPTION
**Pull request by Rohit-Sharmaa**
Description
This pr enhaced the page not found feature.
Fixes #65 
Screenshot/Vides
Screen Recording (05-10-2023 12-16-49)

### CODE REVIEW

**Review by Anandsg — CHANGES_REQUESTED** [review]
bro this looks great, but i feel instead of showing 404 error it would be better if we have such animation with display "Restaurant you're searching does not exists"

**Comment by Rohit-Sharmaa** [comment]
@Anandsg I will try to find that animated gif . After resolving i will make a pr.

**Comment by Rohit-Sharmaa** [comment]
Screen Recording (05-10-2023 20-30-01)

@Anandsg  i thought it would be good ? what do you think

**Comment by Anandsg** [comment]
> Screen Recording (05-10-2023 20-30-01) [ Screen Recording (05-10-2023 20-30-01) ](https://user-images.githubusercontent.com/130988755/272948172-e111de76-16e7-448c-a16f-bfa09b955412.gif) [ ](https://user-images.githubusercontent.com/130988755/272948172-e111de76-16e7-448c-a16f-bfa09b955412.gif)
> 
> @Anandsg i thought it would be good ? what do you think

Brother i think your previous design was good but this is quite over as our app is simple let's find out some simple animations or simple images that perfectly suits our app

**Comment by Rohit-Sharmaa** [comment]
@Anandsg if you want i will revort my changes to previous animated gif i will do that .
But not able to find animated gif that you are taking about.
If you find any animated gif like that you want just add that gif in the assests folder  and after i will implement all the changes.

**Comment by Rohit-Sharmaa** [comment]
ORFI0N0
@Anandsg I think this one is perfect. What do you think ??

**Comment by Anandsg** [comment]
> ORFI0N0 @Anandsg I think this one is perfect. What do you think ??

yeah better

**Comment by Rohit-Sharmaa** [comment]
I will do change and commit .

**Comment by Rohit-Sharmaa** [comment]
Screen Recording (05-10-2023 22-57-39)
@Anandsg  Please review my changes.
and give me feedback??

**Review by Anandsg — CHANGES_REQUESTED** [review]
This seems a bit conflicting; I've noticed that the restaurant error handling image is appearing alongside the message. Frankly, the image doesn't look very appealing; perhaps a cleaner approach would be to display just the message

**Pull request closed without merging**
