### PR TITLE
fix : allignement, spacing issues

### PR DESCRIPTION
**Pull request by rohitroy-github**

### CODE REVIEW

**Comment by rohitroy-github** [comment]
Changes now look like >>> 

image

image

Previous look was >>> 

image

image

**Comment by Anandsg** [comment]
please resolve conflict

**Comment by rohitroy-github** [comment]
@Anandsg Done.

**Comment by Anandsg** [comment]
@rohitroy-github Hey there, it seems your recent changes have had an impact on other features. I've noticed that the 'scroll to top' feature is no longer visible, and there's an issue where the popup display for adding items to favorites hides below the header. This issue doesn't occur on the main site. Could you please investigate and address this?

I'd recommend forking the latest version of the repo and add your changes. It appears that something may have gone awry during conflict resolution.

Regarding your design, when I look at the actual preview, I suggest slightly reducing the size of the restaurant cards; they currently appear quite large. However, I must say that the responsiveness on small devices looks great.

**Pull request closed without merging**
