### PR TITLE
Added login logout

### PR DESCRIPTION
**Pull request by Shahidkhatrii**
Issue:
closes: #10 

This PR does:
Now we can use login logout functionality and it uses oauth using google account for authorization. 

Screenshot:
Screenshot 2023-10-03 223209

### CODE REVIEW

**Comment by Anandsg** [comment]
@Shahidkhatrii I will review these changes and update asap.

**Review by Anandsg — APPROVED** [review]
After checking the code thoroughly, it seems pretty good. It could be even better if a new component is created for the OAuth changes instead of adding them to the Header component, But that's ok overall it's looking fine.

**Comment by Anandsg** [comment]
@Shahidkhatrii  am i making any mistake here, as discussed earlier i have update the client id with my google account and while testing i am getting error like below can you assist me if i am doing anything wrong

I am testing with below client ID 
Screenshot 2023-10-04 at 4 35 17 PM

Code (App.js) :

    path: "/",
    element: (
      <GoogleOAuthProvider clientId="123456789-if48kse03d6ohijbf0hbg48rltvn77po.apps.googleusercontent.com">
        <AppLayout />
      </GoogleOAuthProvider>
    ), 

Error i am receiving : 
Screenshot 2023-10-04 at 4 38 08 PM

**Comment by Shahidkhatrii** [comment]
In your Netlify project settings, navigate to "Settings" > "Access Control" > "OAuth."

Screenshot_20231004_052937
Screenshot_20231004_052847
I think this will work

**Comment by Anandsg** [comment]
@Shahidkhatrii Yeah ok

**Pull request merged**
