### PR TITLE
Added functionality to Cart, added Order Summary

### PR DESCRIPTION
**Pull request by isakshamkumar**
Added order summary as it was shown in the screenshot

https://github.com/Anandsg/Hungry-hero/assets/124489667/419e622f-ac06-4b51-8f71-74d2213b2503

### CODE REVIEW

**Review by Anandsg — COMMENTED** [review]
This look amazing but i see NaN in the order summary is there anything missing over here, see attachment? also it would be more good if we could create new component for orderSummary.

Screenshot 2023-10-10 at 8 23 49 AM

**Comment by isakshamkumar** [comment]
I checked again by adding fresh items to cart and the price,discount ,everything was shown correctly as was shown in the video attachment i provided!

**Comment by isakshamkumar** [comment]
I checked everything and i see the issue is the data recieved by the api, the api is giving different keys for different menu items, 
Screenshot 2023-10-10 122809

see here in the ss provided, the 5th key has categories as a further key whereas the 9th one has itemCards as a key, so thats why issue is there i think

**Comment by isakshamkumar** [comment]
After tons of putting console logs and debugging the inconsistent api data(  :/  ). Finally fixed the issue, please check

**Comment by Anandsg** [comment]
> After tons of putting console logs and debugging the inconsistent api data( :/ ). Finally fixed the issue, please check

Checking

**Comment by Anandsg** [comment]
Looks good did we touched anything for the toast message? i don't see that feature in your preview link
Screenshot 2023-10-10 at 8 17 36 PM

Also when user adds only one item to the add the remove button overlaps the description of the item can we fix that 
Screenshot 2023-10-10 at 8 18 25 PM

**Comment by isakshamkumar** [comment]
Fixed the bug, actually i was handling add item to cart state in other component and thats why the toast function was not executed!

**Comment by Anandsg** [comment]
> https://deploy-preview-139--hungry-hero-ag.netlify.app/

yeah i came to know that, toast message changes make sense, did you looked into other issue? 'the remove button in the cart'

**Comment by Anandsg** [comment]
> Fixed the bug, actually i was handling add item to cart state in other component and thats why the toast function was not executed!

yeah i came to know that, toast message changes make sense, did you looked into other issue? 'the remove button in the cart'

**Comment by isakshamkumar** [comment]
can you please elaborate the issue you are telling about?

**Pull request merged**
