### PR TITLE
Enhance app header with icons

### PR DESCRIPTION
**Pull request by gandholi-kumar**
Hi @Anandsg
Please approve my merge request.

**Task Accomplished:**
- Added icons to header labels.

**Snapshot:**
image
image

### CODE REVIEW

**Review by Anandsg — APPROVED** [review]
Looks good

**Comment by gandholi-kumar** [comment]
Hi @Anandsg  
Can you add the "`hacktoberfest` &  `hacktoberfest-accepted`"

**Comment by gandholi-kumar** [comment]
Hi @Anandsg, 
This merge request is not getting reflected in my HackOctober fest. 
Do you need to add a label to this MR?

**Comment by Anandsg** [comment]
Added

**Pull request merged**
