### PR TITLE
Added Scroll animation

### PR DESCRIPTION
**Pull request by prakhar1535**
decreased the icon size

### CODE REVIEW

**Comment by prakhar1535** [comment]
the merge changes  is howing in my folked repo but not yours why is it so?

**Comment by prakhar1535** [comment]
should i again do a pr ?

**Comment by Anandsg** [comment]
yes please fork newly and add i see some component got conflicted just fixed it. thanks for your patience

**Comment by prakhar1535** [comment]
added a new pr

**Pull request closed without merging**
