### PR TITLE
 [Feature Request] : Add multiple rating filter options to restaurant displaying page #115 ADDED FILTER OPTIONS 4.2+ , high to low , low to high

### PR DESCRIPTION
**Pull request by prakhar1535**
Screenshot 2023-10-08 162807
Screenshot 2023-10-08 163201
Screenshot 2023-10-08 162747
Screenshot 2023-10-08 162801

### CODE REVIEW

**Review by Anandsg — CHANGES_REQUESTED** [review]
Bro filter button looks ugly please investigate how dropdown button looks also i see you randomly edited some component see below 
Screenshot 2023-10-08 at 4 47 12 PM

**Comment by prakhar1535** [comment]
Screenshot 2023-10-08 171629

**Comment by prakhar1535** [comment]
its fine now?

**Comment by Anandsg** [comment]
Take a look at the other buttons as well, and arrange the size the same way. In the dropdown, instead of directly saying '4.2,' change it to 'Top rated.'

**Comment by Anandsg** [comment]
don't touch favourites feature it's already implemented

**Comment by prakhar1535** [comment]
Screenshot 2023-10-08 181921
Pulled recent changes and matched the size

**Pull request closed without merging**
