### PR TITLE
Animated and improved Ui of Faq Section

### PR DESCRIPTION
**Pull request by isakshamkumar**
Animated the Faq section using mui

https://github.com/Anandsg/Hungry-hero/assets/124489667/eee05cea-9497-4429-9b1f-a0f0b55618fa

### CODE REVIEW

**Review by Anandsg — CHANGES_REQUESTED** [review]
Looks good, Can we consider changing the title (Accordion header) color from blue to a different shade, perhaps a dark gray with a semibold font? Let's go with your choice whichever option enhances the overall app aesthetics

**Comment by isakshamkumar** [comment]
> Looks good, Can we consider changing the title (Accordion header) color from blue to a different shade, perhaps a dark gray with a semibold font? Let's go with your choice whichever option enhances the overall app aesthetics

Sure Working on That!

**Review by Anandsg — CHANGES_REQUESTED** [review]
Brother please reduce the title's font size this looks ugly, before pushing send me screenshot i will review and give go ahead also please remove font bold

**Comment by isakshamkumar** [comment]
Sorry about that, working on it

**Comment by isakshamkumar** [comment]
Screenshot 2023-10-07 005639

How's it now?

**Comment by Anandsg** [comment]
> Screenshot 2023-10-07 005639
> 
> How's it now?

Looks good, please create a PR now

**Comment by isakshamkumar** [comment]
Sure thanks for assistance!

**Pull request merged**
