### PR TITLE
[refactor]: contact component - replace with material-ui

### LINKED ISSUE #234: [Refactor]: Replace Input with material UI's Text field & other props refactoring
@Anandsg 

As we have material-ui dependency in the project, shall i refactor all the contact form component input with TextField in the Material-UI.

Adavantages:

1. Enhanced UI Design
2. Easy form controls intergration will be easier on adding material-UI.

Sample Image:

image

### PR DESCRIPTION
**Pull request by Prakash-Ravichandran**
@Anandsg 
Closes #234 

I have refactored the input field/ fucntionality to material-ui.

Refer video - [Contact Component Material UI](https://drive.google.com/file/d/19xeXdc_AAu4pAw4M3Y4K8Tt2qjFrM2Mj/view?usp=sharing)

Kindly review & accept this PR.

Refactored UI:

image

### CODE REVIEW

**Comment by Prakash-Ravichandran** [comment]
@Anandsg 


Update UI with form input icons:

image

**Comment by Anandsg** [comment]
@Prakash-Ravichandran The validations are fine, but don't you think using Tailwind CSS for the contact page would make it look better like previous one and simpler? Why did we opt for Material-UI to build the contact page? Is there any additional benefit that Material-UI provides apart from the page design? i haven't used material UI yet so just curious

**Comment by Prakash-Ravichandran** [comment]
@Anandsg 


Material UI is component specific with lot of customization available than tailwind css(set of default css)


Its like Material UI **Component specific approach vs  CSS is a utility-first** CSS framework.

- **Theming:** Material UI provides powerful theming features to allow for easy customization of the visual styles and colors used in components, while **Tailwind CSS provides a set of default properties** and allows us to define ours by editing the classes upon usage.
- 
- **Presence of a component library:** Material UI provides a comprehensive set of pre-built and customizable components, while Tailwind CSS allows users to build their site components using **its provided utility classes.**
- Availability of utility classes: Tailwind CSS provides more utility classes and customization options than Material UI. Tailwind 
- Learning curve: Material UI is **considered to have a slightly steeper learning curve** due to its extensive component library and theming system than Tailwind CSS, which focuses on utility classes.

**Comment by Anandsg** [comment]
Hey bro I got that why we went with Material UI, considering the entire app is built with TCSS. I thought Material UI might step up the page design, but it didn't quite meet my expectations. Also, when a user hits enter in the 'message' input the form gets submitted, which isn't ideal can we resolve this and tweak the contact page design a bit?

**Comment by Anandsg** [comment]
> @Anandsg
> 
> What you exactly want ?
> 
> I refactored with Material-UI.

can we improve the design of the contact little bit and also i see one bug as above mentioned

**Comment by Prakash-Ravichandran** [comment]
> > @Anandsg


The enter on submit functionality is previously present bro. I never touched that.  

accept  this PR.

will come up with upgraded UI.

**Comment by Anandsg** [comment]
> > > @Anandsg
> 
> The enter on submit functionality is previously present bro. I never touched that.
> 
> accept this PR.
> 
> will come up with upgraded UI & rise them in new PR

see attached clip

https://github.com/Anandsg/Hungry-hero/assets/109084312/12466b9f-ea38-4aeb-b647-089f11e9f5e8

**Comment by Prakash-Ravichandran** [comment]
@Anandsg 

Okay, will refactor this will new design.

Accept this PR.

**Comment by Anandsg** [comment]
If you really want this pull request for Hacktoberfest, I'm willing to accept it. But keep in mind that I won't keep the contact page as it is with these changes. I'll revert it back.

**Comment by Prakash-Ravichandran** [comment]
@Anandsg 

I mentioned, will refer new design & fix the error along with that.

Worked full day for this. Thanks a lot.

**Pull request merged**
