### PR TITLE
fix : Help section fixes

### PR DESCRIPTION
**Pull request by rohitroy-github**
The improved design looks like this : 

image

Please merge the code in accordance with Hacktoberfest if you think that things look okay ! This closes the issue #50

### CODE REVIEW

**Review by Anandsg — CHANGES_REQUESTED** [review]
Your idea is promising, but I've noticed that these accordions seem to be shifting up and down when users collapse and expand them. If you recall, they used to remain firmly in place without any jitter. Could we ensure that they stay fixed in position, even when users collapse and expand them, to maintain a smoother user experience?

**Comment by rohitroy-github** [comment]
I'll check it and let you know.

**Comment by rohitroy-github** [comment]
I have updated the issue with a fix. Things look fine now as you want.

**Review by Anandsg — APPROVED** [review]
This Looks good now.

**Comment by rohitroy-github** [comment]
@Anandsg Please add the Hacktoberfest labels on the PR.

**Pull request merged**
