### PR TITLE
fix (common) : fix footer at bottom

### PR DESCRIPTION
**Pull request by Ravina-Deogadkar**
Fix footer at the bottom.

Closes ticket #5

### CODE REVIEW

**Comment by Anandsg** [comment]
@Ravina-Deogadkar it seems the footer is overlapping with the questionnaire on the help page. Could you please double-check your recent changes to ensure it's fixed at the bottom without any issues

Screenshot 2023-10-02 at 6 58 19 PM

**Comment by Ravina-Deogadkar** [comment]
Fixed it for all pages

image

image

image

**Comment by Anandsg** [comment]
@Ravina-Deogadkar The changes you've implemented are a definite improvement from the previous version. However, I've noticed that the footer is still adjusting its position relative to the body (moving up and down, as seen on the About page). Our aim is to have the footer stay in a fixed position. Can you work on making that adjustment?

**Comment by Ravina-Deogadkar** [comment]
@Anandsg I believe the footer is below you need to scroll the contact page at the bottom to see the footer.
image

If still, this doesn't fulfill the requirement. please assign the ticket to someone else.

**Comment by Anandsg** [comment]
@Ravina-Deogadkar Thanks for the update, appreciate the efforts you put in.

**Pull request closed without merging**
