### PR TITLE
Feature nabvar fixed for all pages

### LINKED ISSUE #160: [Enhancement]: Navbar can be fixed on top
Hey I feel that the Navbar could be fixed at the top . It would be very much convenient for the user. I want to work on the feature. Can I start ?

### PR DESCRIPTION
**Pull request by NilanjanPramanik**
This PR now fix for all the pages. 
Fixes #160 
image
image
image
image

### CODE REVIEW

**Comment by NilanjanPramanik** [comment]
hey @Anandsg now the problem is fixed for all the pages and also if in future there be any new page adding it will also fixed for the navbar

**Comment by NilanjanPramanik** [comment]
I am refixing a little thing.. completing it I will comment here

**Comment by NilanjanPramanik** [comment]
@Anandsg Hey I have fixed all the issues please check it

**Comment by Anandsg** [comment]
Looks good now please resolve the conflict

**Comment by NilanjanPramanik** [comment]
Hey @Anandsg I have used the <Outlet /> inside a div container and gave a overall padding to fix all the pages. Is this the reason for this conflicts? If this is the reason then I will gave padding particularly for all pages.
image

**Comment by Anandsg** [comment]
@NilanjanPramanik Hey, just a heads-up, before I merge your stuff, I had to accept a few tweaks in the body and app.js components. GitHub usually gets all wonky if you fork, push, and then accept new changes. You should probably re-fork the repo and make your changes, then shoot me that PR.

**Comment by NilanjanPramanik** [comment]
@Anandsg  ok I am heading with a new PR

**Pull request closed without merging**
