### PR TITLE
Add Favourite Restaurant Functionality

### PR DESCRIPTION
**Pull request by ShahIsCoding**
Hello @Anandsg 
I have made a few changes to add the feature of favorite Icon such as color changes if the favorite or filter button is selected. 
And to open the card we need to click below the image and other. and other functionality are working fine i have attached few images too.

Screenshot (2)
Screenshot (1)
Screenshot (3)

### CODE REVIEW

**Comment by Anandsg** [comment]
> Hello @Anandsg I have made a few changes to add the feature of favorite Icon such as color changes if the favorite or filter button is selected. And to open the card we need to click below the image and other. and other functionality are working fine i have attached few images too.
> 
> Screenshot (2) Screenshot (1) Screenshot (3)

This looks amazing, Could you please make the cursor change to a pointer when the user hovers over the heart icon? Additionally, is it possible to display a popup or message confirming that the item has been added to the favorites?

**Comment by ShahIsCoding** [comment]
i have added the pointer functionality too ,l  think the there can be a separate issue to make a custom message pop box to display messages and errors

**Comment by Anandsg** [comment]
> Hi @Anandsg,i have added the pointer functionality too, think the there can be a separate issue to make a custom message pop box to display messages and errors.

okay, this looks great could you please add yourself in the readme file as contributor so i will merge this pull request. feel free to create your own feature/issue to this app under hacktoberfest

**Comment by ShahIsCoding** [comment]
hi @Anandsg could u added the Hacktoberfest labels to this

**Comment by Anandsg** [comment]
done @ShahIsCoding

**Pull request merged**
