### PR TITLE
solved issue after remove all item for favorite

### PR DESCRIPTION
**Pull request by ronisarkarexe**
Issue:
closes: #41 

This PR does:

When the user removes all items from their favorites list, they are redirected to the homepage.

### CODE REVIEW

**Comment by Anandsg** [comment]
@ronisarkarexe Could you please cross check, It appears that when a user removes the second last item from their favorites list, they're getting redirected to the home page, even if there's just one item left in their favorites.

Below is the preview shot 

https://github.com/Anandsg/Hungry-hero/assets/109084312/cec53cb5-92ef-4f0f-8683-af5f35faad80

**Comment by ronisarkarexe** [comment]
> @ronisarkarexe Could you please cross check, It appears that when a user removes the second last item from their favorites list, they're getting redirected to the home page, even if there's just one item left in their favorites.
> 
> Below is the preview shot
> 
>  Screen.Recording.2023-10-04.at.11.34.05.AM.online-video-cutter.com.mp4

Sure, thanks.

**Comment by ronisarkarexe** [comment]
> > @ronisarkarexe Could you please cross check, It appears that when a user removes the second last item from their favorites list, they're getting redirected to the home page, even if there's just one item left in their favorites.
> > Below is the preview shot
> > Screen.Recording.2023-10-04.at.11.34.05.AM.online-video-cutter.com.mp4
> 
> Sure, thanks.

Can you please check now?

**Comment by Anandsg** [comment]
Working as expected

**Pull request merged**
