### PR TITLE
Added Meta tags

### PR DESCRIPTION
**Pull request by Krish-Panchani**
#163  - Added Open Graphs & Description meta tags.

### CODE REVIEW

**Comment by Anandsg** [comment]
@Krish-Panchani the app's logo url not working

**Comment by Krish-Panchani** [comment]
> @Krish-Panchani the app's logo url not working

Is there any public URL for Logo?

**Comment by Anandsg** [comment]
Nothing as such, for now keep it as u added i will update the file in future

**Comment by Krish-Panchani** [comment]
@Anandsg added working app's logo url. 
Now you can merge It.

**Pull request merged**
