### PR TITLE
Sticky Navbar and Sort by feature

### PR DESCRIPTION
**Pull request by kmnat**
#47 

WhatsApp Image 2023-10-06 at 12 43 58

### CODE REVIEW

**Review by Anandsg — COMMENTED** [review]
@kmnat  Code changes and feature looks good, could you please resolve the conflict.

**Review by Anandsg — CHANGES_REQUESTED** [review]
I've noticed a bug where the sorting drop-downs on the header become visually unappealing when the user scrolls up. This negatively impacts the user experience.

**Comment by kmnat** [comment]
I've fixed the bug @Anandsg 
WhatsApp Image 2023-10-06 at 13 30 54

**Review by Anandsg — CHANGES_REQUESTED** [review]
Please remove commented consoles else everything looks good.

**Comment by kmnat** [comment]
done @Anandsg

**Comment by kmnat** [comment]
@Anandsg  could you please label it hacktoberfest-accepted? 
It's required for hacktoberfest

**Comment by Anandsg** [comment]
@kmnat done

**Pull request merged**
